#Desafio

#Modifique a função cadastrar_usuario abaixo em que serão coletados as seguintes informações a partir da entrada da pessoa usuária (input):

#Nome
#Idade
#Sexo
#Nesse cadastro busque utilizar namedtuple ou tuplas. Além de aceitar múltiplas entradas do usuário (aceite a opção cadastrar, parar, e lide com uma opção invalida)

#Agora crie uma função que permita descobrir a idade média de pessoas cadastradas pelo sexo (para manter simples, masculino e feminino, representado por m e f, respectivamente).

#Nessa função, perceba que o sexo pode ter sido cadastrado de forma incorreta, como proceder?

#Na função calcule_media_idade_por_sexo o retorno deve ser uma tupla de tuplas no formato

#(('m', ), ('f', ))
#def cadastrar_usuario():

#def calcule_media_idade_por_sexo():
